<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mcnp</string>
		<string>mcnpx</string>
		<string>mcb</string>
		<string>mcnp.php</string>
	</array>
	<key>name</key>
	<string>MCNP MCNPX MCB</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\$.*$</string>
			<key>name</key>
			<string>comment.mcnp</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\/\*</string>
			<key>end</key>
			<string>\*\/</string>
			<key>name</key>
			<string>comment.andrei.mcnp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)^[s]?c.*$</string>
			<key>name</key>
			<string>comment.mcnp</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.serpent</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.serpent</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.mcnp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>imp:n=1</string>
			<key>match</key>
			<string>(\w+)(\:[nphe])?\s*(=)\s*([^\s]+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.mcnp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.mcnp</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.language.serpent</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^[ ]{0,4}([a-z]+)(\d*)(\:[a-z\/]+)?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.mcnp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.mcnp</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.serpent</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^[ ]{0,4}(\*?)(\d+)\s+([a-z\/]+)</string>
			<key>name</key>
			<string>surface.mcnp</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.mcnp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.mcnp</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.character.escaped.mcnp</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^[ ]{0,4}(\d+)\s+(0|(\d+\s+[-0-9.e]+))</string>
			<key>name</key>
			<string>cell.mcnp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(supem)\b</string>
			<key>name</key>
			<string>keyword.control.mcnp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\&amp;\(\)\:\#]</string>
			<key>name</key>
			<string>constant.mcnp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s+\d*[jri]{1}\s+</string>
			<key>name</key>
			<string>constant.mcnp</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.mcnp</string>
	<key>uuid</key>
	<string>A999E929-991F-461C-BFC7-D6F22C588B63</string>
</dict>
</plist>
