<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mcnp.php</string>
		<string>mc(b|np[x]?).(php|erb)</string>
	</array>
	<key>name</key>
	<string>Ruby and PHP (MCNP)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>&lt;\?(php|=|)</string>
			<key>end</key>
			<string>\?&gt;</string>
			<key>include</key>
			<string>source.php</string>
			<key>name</key>
			<string>source.embedded.php.mcnp</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;%</string>
			<key>end</key>
			<string>%&gt;</string>
			<key>name</key>
			<string>source.embedded.ruby.mcnp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.ruby</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(#).*?(?=-?%&gt;)</string>
					<key>name</key>
					<string>source.comment.line.number-sign.ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.ruby</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\%)[^\%]</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.sign.serpent</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>source.embedded.ruby.line.mcbp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.mcnp</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.phpruby.mcnppp</string>
	<key>uuid</key>
	<string>1BCA40A8-D15F-455F-A14D-29D63960F9E5</string>
</dict>
</plist>
